export { default as RightArrow } from '../src/Assets/Icon/rightarrow.svg';
export { default as RightArrow2 } from '../src/Assets/Icon/rightarrow2.svg';
export { default as Currentlocation } from '../src/Assets/Icon/currentlocation.svg';
export { default as CrossIcon } from '../src/Assets/Icon/cross.svg';
export { default as UploadIcon } from '../src/Assets/Icon/upload.svg';
export { default as Upload2Icon } from '../src/Assets/Icon/upload2.svg';
export { default as SearchIcon } from '../src/Assets/Icon/search.svg';
export { default as EditIcon } from '../src/Assets/Icon/edit.svg';
export { default as MappinIcon } from '../src/Assets/Icon/mappin.svg';
export { default as ProfileIcon } from '../src/Assets/Icon/profile.svg';
export { default as Profile2Icon } from '../src/Assets/Icon/profile2.svg';
export { default as CartIcon } from '../src/Assets/Icon/cart.svg';
export { default as ThunderIcon } from '../src/Assets/Icon/thunder.svg';
export { default as ClockIcon } from '../src/Assets/Icon/clock.svg';
export { default as Clock2Icon } from '../src/Assets/Icon/clock2.svg';
export { default as BackIcon } from '../src/Assets/Icon/back.svg';
export { default as HomeIcon } from '../src/Assets/Icon/home.svg';
export { default as Home2Icon } from '../src/Assets/Icon/home2.svg';
export { default as TagIcon } from '../src/Assets/Icon/tag.svg';
export { default as CancelrideIcon } from '../src/Assets/Icon/cancelride.svg';
export { default as PaymentIcon } from '../src/Assets/Icon/payment.svg';
export { default as LocationIcon } from '../src/Assets/Icon/location.svg';
export { default as Location2Icon } from '../src/Assets/Icon/location2.svg';
export { default as ThikIcon } from '../src/Assets/Icon/thik.svg';
export { default as Thik2Icon } from '../src/Assets/Icon/thik2.svg';
export { default as Work2Icon } from '../src/Assets/Icon/work2.svg';
export { default as LogoutIcon } from '../src/Assets/Icon/logout.svg';
export { default as DeleteIcon } from '../src/Assets/Icon/delete.svg';
export { default as MinusIcon } from '../src/Assets/Icon/minus.svg';
export { default as PlusIcon } from '../src/Assets/Icon/plus.svg';
export { default as MenuIcon } from '../src/Assets/Icon/menu.svg';
export { default as AlertcircleIcon } from '../src/Assets/Icon/alertcircle.svg';
export { default as MessageIcon } from '../src/Assets/Icon/message.svg';
export { default as LanguageIcon } from '../src/Assets/Icon/language.svg';
export { default as CalenderIcon } from '../src/Assets/Icon/calender.svg';
export { default as WorkIcon } from '../src/Assets/Icon/work.svg';
export { default as HistoryIcon } from '../src/Assets/Icon/history.svg';
export { default as History2Icon } from '../src/Assets/Icon/history2.svg';
export { default as ThreedotIcon } from '../src/Assets/Icon/threedot.svg';
export { default as ViewIcon } from '../src/Assets/Icon/view.svg';
export { default as StatusIcon } from '../src/Assets/Icon/status.svg';
export { default as CheckboxIcon } from '../src/Assets/Icon/checkbox.svg';
export { default as CheckboxactiveIcon } from '../src/Assets/Icon/checkboxactive.svg';
export { default as HelmateIcon } from '../src/Assets/Icon/helmate.svg';
export { default as CarIcon } from '../src/Assets/Icon/car.svg';
export { default as AccountIcon } from '../src/Assets/Icon/account.svg';
export { default as CallIcon } from '../src/Assets/Icon/call.svg';
export { default as Home } from '../src/Assets/Icon/Vector.svg';
export { default as DateIcon } from '../src/Assets/Icon/akar-icons_schedule.svg';
export { default as VerifiedIcon } from '../src/Assets/Icon/verified.svg';
export { default as Search2Icon } from '../src/Assets/Icon/search2.svg';
export { default as NotificationIcon } from '../src/Assets/Icon/Notification.svg';
export { default as DownarrowIcon } from '../src/Assets/Icon/downarrow.svg';
export { default as UparrowIcon } from '../src/Assets/Icon/uparrow.svg';
export { default as DiscountIcon } from '../src/Assets/Icon/discount.svg';
export { default as TermIcon } from '../src/Assets/Icon/term.svg';
export { default as PrivacyIcon } from '../src/Assets/Icon/privacy.svg';
export { default as InfoIcon } from '../src/Assets/Icon/info.svg';
export { default as FavIcon } from '../src/Assets/Icon/fav.svg';
export { default as UnfavIcon } from '../src/Assets/Icon/unfav.svg';
export { default as TimeIcon } from '../src/Assets/Icon/time.svg';
export { default as StarIcon } from '../src/Assets/Icon/star.svg';
export { default as Cart2Icon } from '../src/Assets/Icon/cart2.svg';
export { default as GridIcon } from '../src/Assets/Icon/grid.svg';
export { default as ThreelineIcon } from '../src/Assets/Icon/threeline.svg';
export { default as Notification2Icon } from '../src/Assets/Icon/notification2.svg';
export { default as AppleIcon } from '../src/Assets/Icon/apple.svg';
export { default as AvocadoIcon } from '../src/Assets/Icon/avocado.svg';
export { default as BlueberryIcon } from '../src/Assets/Icon/blueberry.svg';
export { default as BroccoliIcon } from '../src/Assets/Icon/broccoli.svg';
export { default as ChickenIcon } from '../src/Assets/Icon/chicken.svg';
export { default as ChiliIcon } from '../src/Assets/Icon/chili.svg';
export { default as GarlicIcon } from '../src/Assets/Icon/garlic.svg';
export { default as GingerIcon } from '../src/Assets/Icon/ginger.svg';
export { default as OrangeIcon } from '../src/Assets/Icon/orange.svg';
export { default as SaltIcon } from '../src/Assets/Icon/salt.svg';
export { default as WalnutIcon } from '../src/Assets/Icon/walnut.svg';
export { default as OnionIcon } from '../src/Assets/Icon/onion.svg';
export {default as Cross2Icon} from '../src/Assets/Icon/cross2.svg';
export {default as Cross3Icon} from '../src/Assets/Icon/cross3.svg';
export {default as UserIcon} from '../src/Assets/Icon/user.svg';
export {default as DriverIcon} from '../src/Assets/Icon/driver.svg';
export {default as SellerIcon} from '../src/Assets/Icon/seller.svg';
export {default as OrderIcon} from '../src/Assets/Icon/order.svg';
export {default as TransactionIcon} from '../src/Assets/Icon/transaction.svg';
export {default as GlassIcon} from '../src/Assets/Icon/glass.svg';
export {default as ToprightIcon} from '../src/Assets/Icon/topright.svg';
export {default as DownleftIcon} from '../src/Assets/Icon/downleft.svg';
export {default as WalletIcon} from '../src/Assets/Icon/wallet.svg';
export {default as CookIcon} from '../src/Assets/Icon/cook.svg';
export {default as DoneIcon} from '../src/Assets/Icon/done.svg';
export {default as DeliveredIcon} from '../src/Assets/Icon/delivered.svg';
export {default as WalkIcon} from '../src/Assets/Icon/walk.svg';
export {default as SupportIcon} from '../src/Assets/Icon/support.svg';
export {default as CategoriesIcon} from '../src/Assets/Icon/categories.svg';
export { default as Plus2Icon } from '../src/Assets/Icon/plus2.svg';
export { default as InvoiceIcon } from '../src/Assets/Icon/invoice.svg';
export { default as FavborIcon } from '../src/Assets/Icon/fav-bor.svg';
export { default as ShopIcon } from '../src/Assets/Icon/shop.svg';
export { default as Car5Icon } from '../src/Assets/Icon/car5.svg';
export { default as Location3Icon } from '../src/Assets/Icon/location3.svg';
export { default as Home3Icon } from '../src/Assets/Icon/home3.svg';
export { default as NotesIcon } from '../src/Assets/Icon/notes.svg';
export { default as Profile3Icon } from '../src/Assets/Icon/profile3.svg';
export { default as DirectionIcon } from '../src/Assets/Icon/direction.svg';
export { default as SettingsIcon } from '../src/Assets/Icon/settings.svg';
export { default as CalendarUpIcon } from '../src/Assets/Icon/calendarup.svg';
export { default as CalendarDownIcon } from '../src/Assets/Icon/calendardown.svg';
export { default as SquareCheckIcon } from '../src/Assets/Icon/squarecheck.svg';
export { default as TimerIcon } from '../src/Assets/Icon/timer.svg';
export { default as GrocerybtmwelIcon } from '../src/Assets/Icon/grocerybtmwel.svg';
export { default as CategoryIcon } from '../src/Assets/Icon/category.svg';
export { default as Category2Icon } from '../src/Assets/Icon/category2.svg';
export { default as Shop2Icon } from '../src/Assets/Icon/shop2.svg';
export { default as Profile4Icon } from '../src/Assets/Icon/profile4.svg';
export { default as TruckIcon } from '../src/Assets/Icon/truck.svg';
export { default as EcoIcon } from '../src/Assets/Icon/eco.svg';